# Generated by Django 4.0.3 on 2022-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='publications_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='Число публикаций'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribers_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='Число подписчиков'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='Число подписок'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
