# Generated by Django 4.0.3 on 2022-03-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_publications_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sex'),
        ),
    ]
