# Generated by Django 4.0.3 on 2022-03-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sex_alter_profile_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sex',
            old_name='sex',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.sex'),
        ),
    ]
