# Generated by Django 4.0.3 on 2022-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_sex_sex_title_alter_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='follower', to='accounts.profile'),
        ),
    ]
